### ISSUE TITLE
Try again the sound of the audio was not clear

### ISSUE THREAD

**Issue by jeaprk0504** [Shahabks/myprosody#8]
testfile : testpro.py
wav file : examle - suun3.wav

I used your example... but I have some trouble......
Try again the sound of the audio was not clear......
---------------------------------------------------------------------------------------
$ python3 testpro.py 
[<parselmouth.Data object at 0x7f8c43061030>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c4116ad18>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c41172d18>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c05ec50a0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c050321f0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c0def68f0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c43061030>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c4116ad50>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c41172d50>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c05ec50a0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c050321f0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c0def68f0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c43061030>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c4116ad18>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c41172d18>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c05ec50a0>]
Try again the sound of the audio was not clear
[<parselmouth.Data object at 0x7f8c050321f0>]
Try again the sound of the audio was not clear
Try again the sound of the audio was not clear
Try again the sound of the audio was not clear
---------------------------------------------------------------------------------------

I think myprosody/dataset/essen/myspsolution.praat  have some warning

<line no. 245>
int = Get number of intervals... 2
if int<2
	warning$="A noisy background or unnatural-sounding speech detected. No result try again"
	appendInfoLine: warning$
	exitScript()
endif

int is '1'... 
when I run  testpro.py, myspolution.py executes run_file function.
but run_file returns warning.... so exception is enable....  

How can i fix it???

**Comment by mbcse** [comment]
any solution found

**Comment by Shahabks** [comment]
<line no. 245>
int = Get number of intervals... 2
if int<2

These lines assure the quality of sound-transforming to word-chunks . I cannot speculate why you run into that error when you simulate the sample ...... I need more information to diagnose you issue.........However, if you run to the mentioned warning, perhaps the audio files come with a noisy background, or the audio files are too short, or the files do not contain spoken words or contain stuttering (repeated words)

**Comment by cburst** [comment]
Hi, I'm running into this issue as well. I just wanted to test this script out. The recording sounds quite clear to me, it's about 20 seconds long. Is that not long enough?
[https://www.dropbox.com/s/9ymtqgzg1ps1p4o/wecopy.wav?dl=0](url)

**Comment by Shahabks** [comment]
Sure, 20 secs long audio is long enough to be analyzed. Generally, if the algorithm does not pick up spoken languages in the audio (e.g. noisy backgrounds, sounds of non-spoken languages, repeating short phrases) it will give that warning out. To detect a spoken language, it needs at least 10 to 12 seconds of speech

**Comment by cburst** [comment]
Thanks for the prompt reply. Unfortunately, I'm still getting that error. Is there anyway to debug the script so that I can see where it fails? I'm not really a python expert to be honest (it actually took a lot of work to get the script to run at all; i.e., manually identifying the sound device etc).

**Comment by Shahabks** [comment]
Are your audio files in *.wav format with the specifications mentioned in ReadMe? ... From what you said about "..manually identifying the sound device" make me think that yet your sample audio file needs to be compatible

**Comment by cburst** [comment]
Thanks again for the prompt reply. First, all audio files are generated using the script. Secondly, I have tried 42 khz and 48 khz at 16 bits with no success. Should I try a different frequency/bit rate combination? 
[323-1147.wav.zip](https://github.com/Shahabks/myprosody/files/4366983/323-1147.wav.zip)

**Comment by cburst** [comment]
perhaps i'm missing some dependencies? i noticed that the my-voice-analysis library had not been installed (though the script is still not working for me, it did take longer to fail though)

**Comment by cburst** [comment]
also, my-voice-analysis works GREAT! (tried with a 44 khz file as indicated) perhaps this is all I need for my project. i still want to get SpeechRater working though.

**Comment by cburst** [comment]
also, tried 44 khz 24 bit, still not working

**Comment by cburst** [comment]
ok, i figured it out, all of the language models were missing, manage to get most of them from the myprosody github, but still missing the my_classifier.pickle where might i find that?

**Comment by Shahabks** [comment]
I hope your problem is solved. Please let me know if there is any other

**Comment by bagustris** [comment]
The problem still exist for me, although the wav file clear enough.

**Comment by Shahabks** [comment]
it could happen when the length of recorded audio is short ..... If you
want to capture short audio files (less than 10 sec., if my mind goes
right) you need to change the filter parameters

**Comment by ahalyaj** [comment]
I too had the same issue regarding my audio file. And I constantly get this message("Try again the sound of the audio was not clear") after testing every functions (for eg: mysp.myspsr(p,c)). Can you explain the reason why I get this issue even though the audio is in wav format and not of short duration? Can you please check my audio file, and tell if it works for you?

[my-voice-analysis.zip](https://github.com/Shahabks/myprosody/files/4769082/my-voice-analysis.zip)

**Comment by felixbur** [comment]
Actually i had this problem and what helped me was to copy the myspsolution.praat file to the folder containing the audio.
I guess the error message could be improved.

**Comment by tux103** [comment]
Hi worked it out you have to remove the file extension on the file name. I changed the file name form "myrcording.wav" "myrcording"
